// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJtYerQjYjsHPKkCUcshF6zI02bDswyP8',
    appId: '1:797326129270:web:6aee6aee17d55f6a134757',
    messagingSenderId: '797326129270',
    projectId: 'denso-5113a',
    authDomain: 'denso-5113a.firebaseapp.com',
    storageBucket: 'denso-5113a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5bJaDSA5J2cj59ytDNUh1LakdcMHdclk',
    appId: '1:797326129270:android:60032cae40d5224e134757',
    messagingSenderId: '797326129270',
    projectId: 'denso-5113a',
    storageBucket: 'denso-5113a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Z-ocxLIGsDF7L9paEU4R7acVTRozTCU',
    appId: '1:797326129270:ios:a4335c58bed40739134757',
    messagingSenderId: '797326129270',
    projectId: 'denso-5113a',
    storageBucket: 'denso-5113a.firebasestorage.app',
    iosBundleId: 'com.example.smartfactoryConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Z-ocxLIGsDF7L9paEU4R7acVTRozTCU',
    appId: '1:797326129270:ios:a4335c58bed40739134757',
    messagingSenderId: '797326129270',
    projectId: 'denso-5113a',
    storageBucket: 'denso-5113a.firebasestorage.app',
    iosBundleId: 'com.example.smartfactoryConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJtYerQjYjsHPKkCUcshF6zI02bDswyP8',
    appId: '1:797326129270:web:8d8032d41cc8d9ac134757',
    messagingSenderId: '797326129270',
    projectId: 'denso-5113a',
    authDomain: 'denso-5113a.firebaseapp.com',
    storageBucket: 'denso-5113a.firebasestorage.app',
  );

}